"""Documentation-only checks. Uses the standard library, not the NNPD runtime.

Run from any directory. --html checks a Sphinx HTML output tree. The optional
--verify-original checks this release against the original ZIP's file manifest;
it is deliberately not used by CI, so future application edits remain possible.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import sys
from urllib.parse import unquote, urlsplit

DOCS = Path(__file__).resolve().parent
ROOT = DOCS.parent


def check_sources() -> tuple[dict, list[str]]:
    errors: list[str] = []
    pages = [p for p in DOCS.rglob("*.md")
             if not {"_build", "_validation", ".venv", "autoapi"} & set(p.parts)]
    targets = 0
    snippets = 0
    for page in pages:
        text = page.read_text(encoding="utf-8")
        for index, match in enumerate(re.finditer(r"^```python\n(.*?)^```\s*$", text, re.M | re.S)):
            snippets += 1
            try:
                ast.parse(match.group(1), filename=f"{page.relative_to(ROOT)}:example-{index + 1}")
            except SyntaxError as error:
                errors.append(str(error))
        # Known file-based MyST directives and downloadable files.
        references = re.findall(r"^```\{(?:include|literalinclude|figure|image)\}\s+(.+?)\s*$", text, re.M)
        references += re.findall(r"\{download\}`[^`]*?<([^>]+)>`", text)
        for reference in references:
            if not (page.parent / reference).is_file():
                errors.append(f"{page.relative_to(ROOT)}: missing file {reference}")
            targets += 1
        # Remove code fences before examining ordinary inline Markdown links.
        prose = re.sub(r"^```[^\n]*\n.*?^```\s*$", "", text, flags=re.M | re.S)
        for reference in re.findall(r"\]\(([^\s)]+)\)", prose):
            link = urlsplit(reference)
            if link.scheme or link.netloc or not link.path:
                continue
            destination = (page.parent / unquote(link.path)).resolve()
            if not destination.exists():
                errors.append(f"{page.relative_to(ROOT)}: missing link {reference}")
            targets += 1
        for block in re.findall(r"^```\{toctree\}\n(.*?)^```\s*$", text, re.M | re.S):
            for entry in block.splitlines():
                entry = entry.strip()
                if not entry or entry.startswith(":"):
                    continue
                entry = entry.rsplit("<", 1)[-1].rstrip(">")
                base = (page.parent / entry).resolve()
                if "autoapi" in base.parts:
                    # These files are generated by AutoAPI during the Sphinx build.
                    continue
                if not base.with_suffix(".md").is_file() and not base.with_suffix(".rst").is_file():
                    errors.append(f"{page.relative_to(ROOT)}: missing toctree page {entry}")
                targets += 1
    for source in (DOCS / "conf.py", DOCS / "check.py"):
        try:
            ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
        except SyntaxError as error:
            errors.append(str(error))
    return {"markdown_pages": len(pages), "python_examples_parsed": snippets,
            "source_targets_checked": targets}, errors


class Page(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: set[str] = set()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = dict(attrs)
        if values.get("id"):
            self.ids.add(values["id"])
        if tag == "a" and values.get("name"):
            self.ids.add(values["name"])
        attribute = {"a": "href", "link": "href", "script": "src", "img": "src",
                     "source": "src", "iframe": "src", "form": "action"}.get(tag)
        if attribute and values.get(attribute):
            self.links.append(values[attribute])

    handle_startendtag = handle_starttag


def check_html(directory: Path) -> tuple[dict, list[str]]:
    directory = directory.resolve()
    errors: list[str] = []
    for required in ("index.html", "search.html", "searchindex.js", ".nojekyll"):
        if not (directory / required).is_file():
            errors.append(f"HTML output is missing {required}")
    pages: dict[Path, Page] = {}
    for path in directory.rglob("*.html"):
        page = Page()
        page.feed(path.read_text(encoding="utf-8"))
        pages[path.resolve()] = page
    checked = 0
    for path, page in pages.items():
        for reference in page.links:
            link = urlsplit(reference)
            if link.scheme or link.netloc:
                continue
            if link.path.startswith("/"):
                errors.append(f"{path.relative_to(directory)}: root-relative URL breaks project sites: {reference}")
                continue
            target = (path.parent / unquote(link.path)).resolve() if link.path else path
            if target.is_dir():
                target /= "index.html"
            if not target.is_relative_to(directory) or not target.is_file():
                errors.append(f"{path.relative_to(directory)}: missing local target {reference}")
            elif link.fragment and target in pages and unquote(link.fragment) not in pages[target].ids:
                errors.append(f"{path.relative_to(directory)}: missing fragment {reference}")
            checked += 1
    return {"html_pages": len(pages), "internal_links_and_assets_checked": checked}, errors


def check_original() -> tuple[dict, list[str]]:
    manifest = json.loads((DOCS / "_validation" / "original-files.json").read_text(encoding="utf-8"))
    errors = []
    for relative, expected in manifest["files"].items():
        path = ROOT / relative
        if not path.is_file():
            errors.append(f"Original file is missing: {relative}")
        elif hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            errors.append(f"Original file changed: {relative}")
    return {"original_files_checked": len(manifest["files"])}, errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--html", type=Path, help="Check generated Sphinx HTML links/assets.")
    parser.add_argument("--verify-original", action="store_true", help="Compare original-release file hashes.")
    args = parser.parse_args()
    report, errors = check_sources()
    if args.html:
        result, failures = check_html(args.html)
        report.update(result)
        errors.extend(failures)
    if args.verify_original:
        result, failures = check_original()
        report.update(result)
        errors.extend(failures)
    report["errors"] = errors
    print(json.dumps(report, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
